# Generated by Django 5.1 on 2024-08-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channelId", models.CharField(max_length=255, verbose_name="チャンネルID")),
                ("msg", models.CharField(max_length=255, verbose_name="メッセージ")),
                ("usr", models.CharField(max_length=255, verbose_name="ユーザ")),
                ("start", models.DateField(verbose_name="開始")),
                ("end", models.DateField(verbose_name="終了")),
            ],
        ),
    ]
